server:
  port: 7999

spring:
  application:
    name: jms-provider-activemq
  activemq:
    broker-url: tcp://172.16.5.56:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
    # ActiveMQ对序列化包(类)存在白名单限制，需要将包名加入白名单或者关闭白名单
    packages:
      trust-all: true
#决定默认的连接工厂点对点模式还是发布订阅模式
#  jms:
#    pub-sub-domain: false